# Generated by Django 4.1.3 on 2023-01-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='CreCliNme', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'CreCli',
            },
        ),
    ]
